$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: affection-rf-v33
experiment_name: affection-rf-final
description: End-to-end retrain pipeline (SQL → Train → Register → Deploy)

settings:
  default_compute: azureml:TCBA-A-3

jobs:
  preprocess:
    type: command
    component: azureml:preprocess_sql_fix_v11:1
    inputs:
      sql_server: "asyifadhilah.database.windows.net"
      sql_database: "tcba"
      sql_username: "asyifa"
      sql_password: "TCBAsd004"
      sql_table: "affection"
    outputs:
      output_data: {type: uri_folder}

  train:
    type: command
    component: azureml:train_sql_fix_v12:1
    inputs:
      input_data: ${{parent.jobs.preprocess.outputs.output_data}}
    outputs:
      model_output: {type: uri_folder}
      features_output: {type: uri_folder}
      metrics_output: {type: uri_folder}
      
  register:
    type: command
    component: azureml:register_model_fix_v18:1
    inputs:
      model_path: ${{parent.jobs.train.outputs.model_output}}
      features_path: ${{parent.jobs.train.outputs.features_output}}
      metrics_path: ${{parent.jobs.train.outputs.metrics_output}}
    outputs:
      registered_model_info: {type: uri_file}

  deploy:
    type: command
    component: azureml:deploy_model_fix_v21:1
    inputs:
      model_id: ${{parent.jobs.register.outputs.registered_model_info}}
      endpoint_name: tcba-a-3
      deployment_name: affection-tcba-fix-v6